### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by TiotBenjy** [mitchwadair/tesjs#57]
**Write your question**
Hello, i need help to fix an error when i subscribe to any envent.

my problem is : Cannot read properties of undefined (reading '0')

**Additional context**
the complete error :

Mon, 12 Sep 2022 18:19:08 GMT - TESjs - Adding notification listener for type channel.subscription.gift
Mon, 12 Sep 2022 18:19:08 GMT - TESjs - Subscribing to topic with type channel.subscription.gift and condition [object Object]

TypeError: Cannot read properties of undefined (reading '0')
at EventManager.queueSubscription (/var/www/vhosts/xxxxxxx.fr/xxxxxxxxxx.fr/node_modules/tesjs/lib/events.js:49:29)
at /var/www/vhosts/jesuiskristoff.fr/bot.jesuiskristoff.fr/node_modules/tesjs/lib/tes.js:189:62
at new Promise (<anonymous>)
at TES.subscribe (/var/www/vhosts/jesuiskristoff.fr/bot.jesuiskristoff.fr/node_modules/tesjs/lib/tes.js:189:16)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Environment:**
- OS: UBUNTU 20.04
- Node Version [e.g. 15.3.0]: v16.15.1
- TESjs Version [e.g. 0.1.0]: "tesjs": "^0.7.0",

**Comment by mitchwadair** [comment]
Hmm.. I did some playing around and found what might be the problem.  Does the client ID you're using have the correct authorization scopes?  For [channel.subscription.gift](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelsubscriptiongift), you need the `channel:read:subscriptions` scope.

If you are unsure how to give yourself that scope, you can check out my comment in #13 [here](https://github.com/mitchwadair/tesjs/issues/13#issuecomment-754071206) to get it set up.

As a personal note: filed #58 to improve error messaging here

> BUT evnets sub works correctly I recieve all the event i subscribed

When you say this, do you mean that you're still receiving the events properly?  Are you using the Twitch CLI to test this?

**Comment by TiotBenjy** [comment]
Yes I receive event properly because when I use rewards the event is correctly triggered and message is sent in the chat. Today I'm resub on the channel ans the event works perfectly.

I don't use Twitch CLI.

I don't understand this error ^^

**Comment by mitchwadair** [comment]
I see, okay.  So the other thing that may be happening is that you already had a subscription made with that condition.  If you call
```js
tes.getSubscription("channel.subscription.gift", { broadcaster_user_id: <your-id> }).then(console.log);
```
You'll probably see that you've already made that subscription and that is why your events are functioning properly.  When an existing subscription is present Twitch returns a 409 response when attempting to subscribe to it again.  #58 should also help with this case

**Comment by mitchwadair** [comment]
Just released `v0.7.1` that should provide better output for you

**Comment by TiotBenjy** [comment]
Okay I will update the module and test it.

Thanks !

**Comment by TiotBenjy** [comment]
Yes that's the problem !

Thank you for your help and your reactivity !

Now i have : 
Tue, 13 Sep 2022 15:46:24 GMT - TESjs - Adding notification listener for type channel.subscription.gift
0|Toffibot  | Tue, 13 Sep 2022 15:46:24 GMT - TESjs - Subscribing to topic with type channel.subscription.gift and condition { broadcaster_user_id: 'xxxx' }
Error: 409 Conflict: subscription already exists at TES.subscribe

**Comment by mitchwadair** [comment]
Awesome, glad you got it figured out :+1: 

Happy to help :)
